# Default values for techchallengefastfoodapi118fase2.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: fiaptechchallengelocal  # Replace with your actual image name
  imageName: techchallengefastfoodapi118fase2
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.0"  # Override this with your actual image tag

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}

securityContext: {}

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
service:
  # Default port for ingress and test compatibility
  port: 80
  instances:      
# Configuration to test the api that runs inside cluster
    - name: fastfood-api-nodeport
      type: NodePort
      port: 80
      targetPort: 8080
      nodePort: 30080
      portName: http

# This block is for setting up the ingress for more information can be found here: https://kubernetes.io/docs/concepts/services-networking/ingress/
ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe:
  httpGet:
    path: /healthz  # Update this to match your API's health endpoint
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
readinessProbe:
  httpGet:
    path: /healthz  # Update this to match your API's health endpoint
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 10
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []

# ConfigMap configuration
configMap:
  enabled: true
  name: "tech-challenge-fast-food-api-fase2"  # If empty, will use the chart fullname
  annotations: {}
  # ConfigMap data - these values will be stored as plain text
  data:
    # Application configuration
    LOGGING__LOGLEVEL: "Information"
    AllowedHosts: "*"    

    # Configure JWT Timer
    Jwt__ExpirationMinutes: "60"

  # Mercado Pago configuration
    MercadoPago__NotificationUrl: "https://webhook.site/8a7b20a7-0eab-4645-899c-17d419361fbd"

  # Environment variables to create from configMap keys
  envVars:
    - name: "LOGGING__LOGLEVEL"
      configMapKey: "LOGGING__LOGLEVEL"
      
    - name: "AllowedHosts"
      configMapKey: "AllowedHosts"

    - name: "Jwt__ExpirationMinutes"
      configMapKey: "Jwt__ExpirationMinutes"

    - name: "MercadoPago__NotificationUrl"
      configMapKey: "MercadoPago__NotificationUrl"      

# Secret configuration
secret:
  enabled: true
  name: "tech-challenge-fast-food-api-fase2"  # If empty, will use the chart fullname
  annotations: {}
  # Secret data - these values will be base64 encoded automatically
  data:
    # JWT Variables
    Jwt__Key: "08fa1d833b85a776166dd0a30ec21687"
    Jwt__Issuer: "http://localhost:8080"
    Jwt__Audience: "http://localhost:8080"

    # Security Key
    Security__Key: "ea9083a270357e95a1bdb53188a66bb4"

    # Mercado Pago configuration
    MercadoPago__BaseUrl: "https://api.mercadopago.com"
    MercadoPago__AccessToken: "APP_USR-306289084918862-072219-fa7e95087dbe33b631ffe685a321f0f9-2430042968"
    MercadoPago__UserId: "2430042968"
    MercadoPago__PosId: "POS01"

    #Database configuration
    ConnectionStrings__DefaultConnection: "Data Source=sqlserver-clusterip, 1433;Database=TechChallengeFastFoodFase2;Integrated Security=false;User ID=sa;Password=Mssql!Passw0rd;TrustServerCertificate=true;Max Pool Size=200;Min Pool Size=10;Connection Timeout=30;"

  # Environment variables to create from secret keys
  envVars:
    - name: "Jwt__Key"
      secretKey: "Jwt__Key"

    - name: "Jwt__Issuer"
      secretKey: "Jwt__Issuer"

    - name: "Jwt__Audience"
      secretKey: "Jwt__Audience"

    - name: "Security__Key"
      secretKey: "Security__Key"      

    - name: "MercadoPago__BaseUrl"
      secretKey: "MercadoPago__BaseUrl"

    - name: "MercadoPago__AccessToken"
      secretKey: "MercadoPago__AccessToken"

    - name: "MercadoPago__UserId"
      secretKey: "MercadoPago__UserId"

    - name: "MercadoPago__PosId"
      secretKey: "MercadoPago__PosId"

    - name: "ConnectionStrings__DefaultConnection"
      secretKey: "ConnectionStrings__DefaultConnection"

nodeSelector: {}

tolerations: []

affinity: {}
