<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>TechChallengeFastFood.CleanArch.Domain.Entities</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Common\Common.Dto\Common.Dto.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Customer\Exceptions\" />
      <Folder Include="Payments\Exceptions\" />
    </ItemGroup>

</Project>
