services:
  techchallengefastfoodapi118fase2:
    image: techchallengefastfoodapi118fase2
    ports:
      - '8080:8080'
      - '8081:8081'
    depends_on:
      - sqldatabasetechchallenge118fase2
    environment:
      ConnectionStrings__DefaultConnection: ""
      Jwt__Key: ""
      Jwt__Issuer: ""
      Jwt__Audience: ""
      Jwt__ExpirationMinutes: "60"
      MercadoPago__BaseUrl: ""
      MercadoPago__AccessToken: ""
      MercadoPago__UserId: ""
      MercadoPago__PosId: ""
      MercadoPago__SponsorId: 
      MercadoPago__NotificationUrl: ""
    restart: on-failure:5
    deploy:
      resources:
        limits:
          memory: 300MB
          cpus: 0.4
    healthcheck:
      test: curl --fail http://localhost:8080/healthz || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    build:
      context: .
      dockerfile: src/CleanArchitecture/Infrastructure/TechChallengeFastFood.CleanArch.Infrastructure.API/Dockerfile
  
  sqldatabasetechchallenge118fase2:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqldatabasetechchallenge118fase2
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'Mssql!Passw0rd'
    restart: unless-stopped
    volumes:
      - mssql_data:/var/opt/mssql
    deploy:
      resources:
        limits:
          memory: 1GB

volumes:
  mssql_data: { }