<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Application\TechChallengeFastFood.CleanArch.Application.UseCases\TechChallengeFastFood.CleanArch.Application.UseCases.csproj" />
    </ItemGroup>

</Project>
