name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: 'techchallengefastfoodapi118fase2.azurecr.io'
  IMAGE_NAME: 'techchallengefastfoodapi118fase2'
  HELM_CHART_NAME: 'techchallengefastfoodapi118fase2' 
  DOTNET_VERSION: '8.0.x'  # Adjust to your current .NET version

    #   REGISTRY: ${{ vars.DOCKER_REGISTRY }} # your-acr-name.azurecr.io
#   IMAGE_NAME: ${{ vars.DOCKER_IMAGE_NAME }} #your-app-name
#   HELM_CHART_NAME: ${{ vars.HELM_CHART_NAME }} #your-helm-chart
#   DOTNET_VERSION: '8.0.x'  # Adjust to your current .NET version



jobs:
  build-dotnet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build .NET application
      run: dotnet build --no-restore --configuration Release

  build-docker:
    needs: build-dotnet
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4    

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=raw,value=pr-${{ github.event.pull_request.number }}
          type=sha,prefix={{branch}}
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build Docker image (All branches)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    